# Generated by Django 3.2.9 on 2023-11-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_listapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
